development:
  adapter: mysql2
  encoding: utf8
  database: sample_app_development
  username: root
  password:
  pool: 10
  reconnect: false

test: &test
  adapter: mysql2
  encoding: utf8
  database: sample_app_test
  username: root
  password:
  pool: 10
  reconnect: false

production:
  adapter: mysql2
  encoding: utf8
  database: sample_app_devlopement
  username: root
  password:
  pool: 10
  reconnect: false
cucumber:
  <<: *test